export const Matches = [
  {
    id: 1,
    homeTeam: "ahly",
    awayTeam: "zamalek",
    matchVenue: "Cairo Stadium",
    date: "3/1/2024",
    time: "13:00",
    lineman1: "ahmad",
    lineman2: "ali",
    vacantSeats: 5,
    reservedSeats: 10,
  },
  {
    id: 2,
    homeTeam: "ahly",
    awayTeam: "liverpool",
    matchVenue: "Alex Stadium",
    date: "4/4/2024",
    time: "17:00",
    lineman1: "fouda",
    lineman2: "badr",
    vacantSeats: 8,
    reservedSeats: 1,
  },
  {
    id: 3,
    homeTeam: "barca",
    awayTeam: "liverpool",
    matchVenue: "Suez Stadium",
    date: "4/3/2024",
    time: "09:00",
    lineman1: "malak",
    lineman2: "reem",
    vacantSeats: 8,
    reservedSeats: 23,
  },
  {
    id: 3,
    homeTeam: "barca",
    awayTeam: "liverpool",
    matchVenue: "Suez Stadium",
    date: "4/3/2024",
    time: "09:00",
    lineman1: "malak",
    lineman2: "reem",
    vacantSeats: 8,
    reservedSeats: 23,
  },
  {
    id: 3,
    homeTeam: "barca",
    awayTeam: "liverpool",
    matchVenue: "Suez Stadium",
    date: "4/3/2024",
    time: "09:00",
    lineman1: "malak",
    lineman2: "reem",
    vacantSeats: 8,
    reservedSeats: 23,
  },
  {
    id: 3,
    homeTeam: "barca",
    awayTeam: "liverpool",
    matchVenue: "Suez Stadium",
    date: "4/3/2024",
    time: "09:00",
    lineman1: "malak",
    lineman2: "reem",
    vacantSeats: 8,
    reservedSeats: 23,
  },
  {
    id: 3,
    homeTeam: "barca",
    awayTeam: "liverpool",
    matchVenue: "Suez Stadium",
    date: "4/3/2024",
    time: "09:00",
    lineman1: "malak",
    lineman2: "reem",
    vacantSeats: 8,
    reservedSeats: 23,
  },
  {
    id: 3,
    homeTeam: "barca",
    awayTeam: "liverpool",
    matchVenue: "Suez Stadium",
    date: "4/3/2024",
    time: "09:00",
    lineman1: "malak",
    lineman2: "reem",
    vacantSeats: 8,
    reservedSeats: 23,
  },
];
