export const StadiumSeats = [
    {
        seatName:"1",
        booked:false,
    },
    {
        seatName:"2",
        booked:false,
    },
    {
        seatName:"3",
        booked:false,
    },
    {
        seatName:"4",
        booked:false,
    },
    {
        seatName:"5",
        booked:false,
    },
    {
        seatName:"6",
        booked:false,
    },
    {
        seatName:"7",
        booked:false,
    },
    {
        seatName:"8",
        booked:false,
    },
    {
        seatName:"9",
        booked:false,
    },
    {
        seatName:"10",
        booked:false,
    },
    {
        seatName:"11",
        booked:false,
    },
    {
        seatName:"12",
        booked:false,
    },
    {
        seatName:"13",
        booked:false,
    },
    {
        seatName:"14",
        booked:false,
    },
    {
        seatName:"15",
        booked:false,
    },
    {
        seatName:"16",
        booked:false,
    },
    {
        seatName:"17",
        booked:false,
    },
    {
        seatName:"18",
        booked:false,
    },
    {
        seatName:"19",
        booked:false,
    },
    {
        seatName:"20",
        booked:false,
    },
];
