export const componentArray = [
    {
        seatName:"a1",
        booked:false,
    },
    {
        seatName:"a2",
        booked:false,
    },
    {
        seatName:"a3",
        booked:false,
    },
    {
        seatName:"a4",
        booked:false,
    },
    {
        seatName:"a5",
        booked:false,
    },
    {
        seatName:"a6",
        booked:false,
    },
    {
        seatName:"a5",
        booked:false,
    },
    {
        seatName:"a6",
        booked:false,
    },
    {
        seatName:"a5",
        booked:false,
    },
    {
        seatName:"a6",
        booked:false,
    },
    {
        seatName:"a5",
        booked:false,
    },
    {
        seatName:"a6",
        booked:false,
    },
    {
        seatName:"a5",
        booked:false,
    },
    {
        seatName:"a6",
        booked:false,
    },
    {
        seatName:"a5",
        booked:false,
    },
    {
        seatName:"a6",
        booked:false,
    },
    {
        seatName:"a5",
        booked:false,
    },
    {
        seatName:"a6",
        booked:false,
    },
    {
        seatName:"a5",
        booked:false,
    },
    {
        seatName:"a6",
        booked:false,
    },
];
